"""initial schema and teams

Revision ID: ced154280696
Revises: 
Create Date: 2025-11-05 14:02:59.425759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ced154280696'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_members',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'user_id')
    )
    op.drop_index('ix_artifacts_run_id', table_name='artifacts')
    op.alter_column('project_files', 'use_summary_for_generation',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether to use summary text instead of native file during scope generation',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('project_files', 'native_token_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Token count for the native file (before summarization)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index('ix_project_files_project_id', table_name='project_files')
    op.add_column('projects', sa.Column('team_id', sa.UUID(), nullable=True))
    op.drop_index('ix_projects_owner_id', table_name='projects')
    op.drop_constraint('projects_owner_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'teams', ['team_id'], ['id'])
    op.drop_index('ix_run_steps_run_id', table_name='run_steps')
    op.drop_index('ix_runs_extracted_variables_artifact_id', table_name='runs')
    op.drop_index('ix_runs_parent_run_id', table_name='runs')
    op.drop_index('ix_runs_project_id', table_name='runs')
    op.alter_column('scope_embeddings', 'doc_kind',
               existing_type=sa.TEXT(),
               type_=sa.String(length=40),
               existing_nullable=False)
    op.alter_column('scope_embeddings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_scope_embeddings_embedding', table_name='scope_embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index('idx_scope_embeddings_project', table_name='scope_embeddings')
    op.drop_constraint('scope_embeddings_project_id_fkey', 'scope_embeddings', type_='foreignkey')
    op.create_foreign_key(None, 'scope_embeddings', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scope_embeddings', type_='foreignkey')
    op.create_foreign_key('scope_embeddings_project_id_fkey', 'scope_embeddings', 'projects', ['project_id'], ['id'])
    op.create_index('idx_scope_embeddings_project', 'scope_embeddings', ['project_id'], unique=False)
    op.create_index('idx_scope_embeddings_embedding', 'scope_embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('scope_embeddings', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scope_embeddings', 'doc_kind',
               existing_type=sa.String(length=40),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index('ix_runs_project_id', 'runs', ['project_id'], unique=False)
    op.create_index('ix_runs_parent_run_id', 'runs', ['parent_run_id'], unique=False)
    op.create_index('ix_runs_extracted_variables_artifact_id', 'runs', ['extracted_variables_artifact_id'], unique=False)
    op.create_index('ix_run_steps_run_id', 'run_steps', ['run_id'], unique=False)
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_owner_id_fkey', 'projects', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_projects_owner_id', 'projects', ['owner_id'], unique=False)
    op.drop_column('projects', 'team_id')
    op.create_index('ix_project_files_project_id', 'project_files', ['project_id'], unique=False)
    op.alter_column('project_files', 'native_token_count',
               existing_type=sa.INTEGER(),
               comment='Token count for the native file (before summarization)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('project_files', 'use_summary_for_generation',
               existing_type=sa.BOOLEAN(),
               comment='Whether to use summary text instead of native file during scope generation',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index('ix_artifacts_run_id', 'artifacts', ['run_id'], unique=False)
    op.drop_table('team_members')
    op.drop_table('teams')
    # ### end Alembic commands ###
